heat_template_version: 2013-05-23

description: Two servers with server2 pinging server1 during it's first boot

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: cirros-0.3.3-x86_64
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.tiny
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: heat-instances-key
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: demo-net

resources:   
  server1:
    type: OS::Nova::Server
    properties:
      name: server1
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      image: { get_param: image }
      networks:
        - network: { get_param: private_network }     

  server2:
    type: OS::Nova::Server
    properties:
      name: server2
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      image: { get_param: image }
      networks:
        - network: { get_param: private_network }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            ping -c 10 ip_address
          params:
            "ip_address": { get_attr: [server1, first_address] }
      user_data_format: RAW

outputs:
  server1_name:
    description: Name of the instance 1
    value: { get_attr: [server1, name] }
  server1_ip:
    description: IP address of the instance
    value: { get_attr: [server1, first_address] }
  server2_name:
    description: Name of the instance 2
    value: { get_attr: [server2, name] }
  server2_ip:
    description: IP address of the instance
    value: { get_attr: [server2, first_address] }