heat_template_version: 2013-05-23

description: Simple template to deploy a puppet master connected to the internet

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: ubuntu-trusty-amd64
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: demo-key
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: demo-net
  floating_ip_id:
    type: string
    label: Floating IP ID
    description: Floating ip adress. $ neutron floatingip-list
    default: 59f5c4b4-91a7-4c9c-bdf9-18541ca1a8a6
  ec2-user_password:
    type: string
    label: Modified root password
    default: popito225

resources:  
  puppetmaster_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: private_network }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            echo ec2-user:'$USER_PASSWORD' | /usr/sbin/chpasswd    
            sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/"   /etc/ssh/sshd_config
            service ssh restart
            sleep 20
            ping -c 20 192.168.17.1
            apt-get -y update
          params:
            "$USER_PASSWORD": { get_param: ec2-user_password }            
  association:
     type: OS::Neutron::FloatingIPAssociation
     properties:
       floatingip_id: { get_param: floating_ip_id }
       port_id: {get_attr: [puppetmaster_instance, addresses, {get_param: private_network}, 0, port]}

outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [puppetmaster_instance, name] }
  instance_ips:
    description: IP addresses of the instance
    value: { get_attr: [puppetmaster_instance, addresses] }
  root_password:
    description: Autogenerated value (in theory) of the root password
    value: { get_param: root_password }
