heat_template_version: 2013-05-23
description: >
    two servers deployment at the time
parameters:
  ImageID:
    type: string
    description: Name of image to use for servers
    default: ubuntu-trusty-amd64
  NetID:
    type: string
    label: Network ID
    description: sub-network ID for the servers
  KeyName:
    type: string
    label: Key Pair Name
    description: server ssh key-pair
  InstanceType:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.tiny
    constraints:
      - allowed_values: 
        - m1.tiny
        - m1.small
        description: Value must be one of m1.tiny or m1.small

resources:   
  server1:
    type: OS::Nova::Server
    properties:
      name: server1
      flavor: { get_param: InstanceType }
      key_name: { get_param: KeyName }
      image: { get_param: ImageID }
      networks:
        - network: { get_param: NetID }
  server2:
    type: OS::Nova::Server
    properties:
      name: server2
      flavor: { get_param: InstanceType }
      key_name: { get_param: KeyName }
      image: { get_param: ImageID }
      networks:
        - network: { get_param: NetID }

outputs:
  server1_provider_ip:
    description: IP address of server1 in provider network
    value: { get_attr: [ server1, first_address ] }
  server2_provider_ip:
    description: IP address of server2 in provider network
    value: { get_attr: [ server2, first_address ] }