heat_template_version: 2013-05-23
description: AutoScaling Mediawiki connected to puppetmaster
parameters:
  image:
    type: string    
    description: Image to be used for compute instance    
  flavor:
    type: string    
    description: Type of instance (flavor) to be used    
  key_name:
    type: string    
    description: Name of key-pair to be used for compute instance
  metadata:
    type: json
  private_network:
    type: string
    description: Network to attach instance to.
  wiki_secgroup:
    type: string
    description: wiki security group
  pool_id:
    type: string
    description: Pool to contact
  ec2-user_password:
    type: string    
    hidden: true
  puppetmaster_server_ip:
    type: string
    label: Puppetmaster IP address for wiki instances configuration
  puppetmaster_server_name:
    type: string
    label:  puppetmaster server hostname for wiki instances configuration

resources:
  instance_name:
    type: OS::Heat::RandomString
    properties:
      length: 10

  private_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - default
        - { get_param: wiki_secgroup }

  wiki_instance:
    type: OS::Nova::Server
    properties:
      admin_pass: popito225
      image: { get_param: image }
      flavor: { get_param: flavor }    
      name:
        str_replace:
          template: |
            wiki-pool-suffix
          params: 
            suffix: { get_resource: instance_name}  
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource : private_port }
      metadata: {get_param: metadata}
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            service ssh stop

            ## hostname in /etc/hosts
            ## we use bash to avoid heat circular dependencies if we tried to get the ip address with get_attr instead
            ## we would have done this into the current template : { get_attr: [puppetmaster_instance, first_address] }                
            echo "$(ifconfig eth0|awk -F':' '/inet addr/ {print $2}'|awk '{print $1}') wiki-pool-$INSTANCE_NAME" >> /etc/hosts
            echo '$PUPPETMASTER_IP $PUPPETMASTER_HOSTNAME' >> /etc/hosts

            ## Changing root password (not really useful, but just to show it's possible)
            echo ec2-user:'$USER_PASSWORD' | /usr/sbin/chpasswd    
            echo 'LC_ALL=en_US.UTF-8' >> /etc/environment

            #Prepare puppet
            curl -O https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
            dpkg -i puppetlabs-release-trusty.deb

            # Refresh apt cache
            apt-get -y update
            apt-get -y install puppet git

            # configure Puppet as an agent
            echo '[agent]' >> /etc/puppet/puppet.conf
            echo 'server = $PUPPETMASTER_HOSTNAME' >> /etc/puppet/puppet.conf
            puppet agent --enable
            puppet agent --verbose --no-daemonize --onetime

            apt-get moo
            service ssh start
          params:
            "$USER_PASSWORD": { get_param: ec2-user_password }
            "$INSTANCE_NAME": { get_resource: instance_name }
            "$PUPPETMASTER_IP": { get_param: puppetmaster_server_ip }
            "$PUPPETMASTER_HOSTNAME": { get_param: puppetmaster_server_name }
            
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [wiki_instance, first_address]}
      protocol_port: 80

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [wiki_instance, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }